build:
	dotnet build
run:
	export ASPNETCORE_ENVIRONMENT=Development
	#dotnet ./bin/Debug/netcoreapp3.1/StreamChat.Cli.dll entity=token action=get --debug=true
	dotnet ./bin/Debug/netcoreapp3.1/StreamChat.Cli.dll entity=channelType action=list --debug=true
	#dotnet ./bin/Debug/netcoreapp3.1/StreamChat.Cli.dll entity=channelType action=get name=messaging --debug=true
