build:
	dotnet build
run:
	export ASPNETCORE_ENVIRONMENT=Development
	#dotnet ./bin/Debug/netcoreapp3.1/StreamChat.Cli.dll userToken create --username=SuperUser
	#dotnet ./bin/Debug/netcoreapp3.1/StreamChat.Cli.dll channelType list
	dotnet ./bin/Debug/netcoreapp3.1/StreamChat.Cli.dll channelType get --name=messaging
